Tomorrow fragment layout
develhope/Android6-Team1-ForecastApp pull request #5
Opened 2023-09-12 23:46 UTC by Salvat0tu

i created the mockup version of the tomorrow screen, implemented the bottom nav,

2023-09-13 06:00 UTC, vincenzocostagliola requested changes

2023-09-13 06:00 UTC, vincenzocostagliola commented on app/src/main/java/co/develhope/meteoapp/TomorrowAdapter.kt
> +    RecyclerView.Adapter<TomorrowAdapter.TomorrowViewHolder>() {
Perchè estendiamo il viewholder specifico e non quello generico? La schermatat usa ha più di una view da visualizzare e quindi più viewholder

2023-09-13 06:00 UTC, vincenzocostagliola commented on app/src/main/java/co/develhope/meteoapp/TomorrowAdapter.kt
> +        holder.binding.itemOur.text = model.item_our
Tutte le operazione relative alle view devono essere spostate all'interno del viewholder e non chiamate esternamente

2023-09-13 06:00 UTC, vincenzocostagliola commented on app/src/main/java/co/develhope/meteoapp/TomorrowData.kt
> +    val item_our: String,
i valori di una data class per convenzione hanno nomi in inglese e con la lettera iniziale in minuscolo

2023-09-13 06:00 UTC, vincenzocostagliola commented on app/src/main/java/co/develhope/meteoapp/TomorrowData.kt
> +    //cardview
visto che la data class ha sia i dati per la row che per la card cerca di accorpare i dati in altre data class così da rendere il codice più leggibile

2023-09-13 06:00 UTC, vincenzocostagliola commented on app/src/main/java/co/develhope/meteoapp/TomorrowFragment.kt
> +            listOf(
Dovo arrivano i dati? Dovresti creare una classe repository o più semplicemente un object Data dove recuperare i dati che poi userai per generare la lista (che rappresenta la ui) da dare all'adapter.

2023-09-13 06:00 UTC, vincenzocostagliola commented on app/src/main/java/co/develhope/meteoapp/TomorrowFragment.kt
> +                    "14°", "1/10", "Umidità", "Vento", "70%",
Le lables, se sono statiche, non vanno mandate nella lista da dare all'adapter. Le puoi inserire nella ui utulizzando il file delle stringhe.
In questo modo risolvi il problema della localizzazione e snellisci il codice che stati utilizzando perchè devi mandare meno dati

2023-09-13 06:00 UTC, vincenzocostagliola commented on app/src/main/java/co/develhope/meteoapp/TomorrowFragment.kt
> +                    "01:00", R.drawable.fluent_emoji_crescent_moon, "15°",
Idem per le risorse delle  immagini

2023-09-13 06:00 UTC, vincenzocostagliola commented on app/src/main/res/layout/fragment_tomorrow.xml
> +        android:text="@string/Clima"
le risorse stringa iniziano sempre con la minuscola

2023-09-13 06:00 UTC, vincenzocostagliola commented on app/src/main/res/layout/fragment_tomorrow.xml
> +        android:id="@+id/Tomorrowinfo"
gli id iniziano sempre con la minuscola

2023-09-13 06:00 UTC, vincenzocostagliola commented on app/src/main/res/layout/fragment_tomorrow.xml
> +    android:padding="16dp"
ltutte le risorse, comprese le dimensioni, non devono essere hardcoded ma inserte nel proprio file delle risorse

2023-10-06 14:54 UTC, Catachthonius approved these changes

2023-10-06 14:56 UTC, Catachthonius approved these changes

2023-10-06 15:01 UTC, vincenzocostagliola approved these changes

2023-10-06 15:04 UTC, merged